name: Auto Create Branch and PR

on:
  push:
    branches:
      - main  # Se déclenche à chaque push su  r main

jobs:
  create_branch_and_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Configurer Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Créer une nouvelle branche feature
        run: |
          BRANCH_NAME="feature/auto-${{ github.run_number }}"
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Créer une Pull Request automatiquement
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.BRANCH_NAME }}
          base: main
          title: "PR automatique depuis ${{ env.BRANCH_NAME }}"
          body: "Cette PR a été générée automatiquement."
