name: Dockerized FizzBuzz Tests

on:
  push:
    branches:
      - main
      - docker  # Déclenche l'action sur la branche Docker
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Construire et tester avec Docker
        run: |
          docker build -t fizzbuzz-image .
          docker run --rm fizzbuzz-image
