name: Docker Build & Test

on:
  push:
    branches:
      - docker1  
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Créer un répertoire temporaire pour l'image Docker
        run: |
          mkdir temp_docker_build
          cp -r * temp_docker_build/

      - name: Construire l'image Docker
        run: |
          docker build -t fizzbuzz-image temp_docker_build

      - name: Lancer les tests avec Docker
        run: |
          docker run --rm fizzbuzz-image
