name: Run Pytest in Docker 

on:
  push:
    branches:
      - feature_branch  
  pull_request:
    branches:
      - main  

jobs:
  tests:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Récupère le code source

      - name: Run tests inside Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            python:3.9 \
            bash -c "pip install pytest && pytest"
