name: FizzBuzz Tests 

on:
  push:  
    branches: #
      - main  
  pull_request:  
    branches:
      - main  
  workflow_dispatch:  

jobs:
  test:  
    runs-on: ubuntu-latest  

    steps:
      - name: Cloner le dépôt  
        uses: actions/checkout@v3  

      - name: Configurer Python et installer les dépendances  
        uses: actions/setup-python@v4  
        with:
          python-version: "3.10"  
      
      - name: Installer les dépendances  
        run: |
          python -m pip install --upgrade pip  
          pip install -r requirements.txt || echo "No requirements.txt found"  

      - name: Exécuter les tests unitaires  
        run: |
          pip install unittest-xml-reporting  
          python -m xmlrunner discover -o test-reports/  
          python test_unitaire.py  

      - name: Explorer le concept de "code coverage"  
        run: |
          pip install coverage  
          coverage run -m unittest discover  
          coverage report -m > coverage.txt  # Sauvegarde le rapport dans un fichier

      - name: Commit et push des modifications sur une nouvelle branche  
          run: |
            git config --global user.name "github-actions"
            git config --global user.email "actions@github.com"
            
            git checkout -b update-readme  # Crée une nouvelle branche
            git add README.md
            git commit -m "Mise à jour automatique du README avec le code coverage"
            git push origin update-readme  # Pousse sur la nouvelle branche
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Créer une Pull Request pour fusionner dans main  
          run: |
            gh pr create --title "Mise à jour automatique du README" --body "Cette PR met à jour automatiquement le README avec le taux de couverture des tests." --base main --head update-readme
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
