name: FizzBuzz Tests 

on:
  push:  
    branches: #
      - main  
  pull_request:  
    branches:
      - main  
  workflow_dispatch:  

jobs:
  test:  
    runs-on: ubuntu-latest  

    steps:
      - name: Cloner le dépôt  
        uses: actions/checkout@v3  

      - name: Configurer Python et installer les dépendances  
        uses: actions/setup-python@v4  
        with:
          python-version: "3.10"  
      
      - name: Installer les dépendances  
        run: |
          python -m pip install --upgrade pip  
          pip install -r requirements.txt || echo "No requirements.txt found"  

      - name: Exécuter les tests unitaires  
        run: |
          pip install unittest-xml-reporting  
          python -m xmlrunner discover -o test-reports/  
          python test_unitaire.py  

      - name: Explorer le concept de "code coverage"  
        run: |
          pip install coverage  
          coverage run -m unittest discover  
          coverage report -m > coverage.txt  # Sauvegarde le rapport dans un fichier

      - name: Mettre à jour le README.md avec la couverture  
        run: |
          echo "## Couverture de code" > README.md
          echo "" >> README.md
          echo '```' >> README.md
          cat coverage.txt >> README.md  # Ajoute le rapport de couverture
          echo '```' >> README.md

      - name: Commit et push des modifications  
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Mise à jour automatique du README avec le code coverage"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
