name: FizzBuzz Tests

on:
  push:
    branches:
      - main  # Le workflow se déclenche lorsqu'il y a un push sur la branche 'main'
  pull_request:
    branches:
      - main  # Le workflow se déclenche aussi lorsqu'une PR est ouverte ou mise à jour pour la branche 'main'

jobs:
  test:
    runs-on: ubuntu-latest  # Utilise la dernière version d'Ubuntu pour exécuter les tests

    steps:
      - name: Checkout repository  # Étape pour récupérer le code du dépôt
        uses: actions/checkout@v3  # Action GitHub officielle pour récupérer le code source du dépôt

      - name: Set up Python  # Étape pour configurer Python
        uses: actions/setup-python@v4  # Action GitHub officielle pour installer Python
        with:
          python-version: '3.9'  # Version de Python à installer (ici, la version 3.9)

      - name: Install dependencies  # Étape pour installer les dépendances nécessaires
        run: |
          pip install pytest
          pip install coverage

      - name: Run tests  # Étape pour lancer les tests
        run: coverage run -m unittest discover tests  # Utiliser coverage pour exécuter les tests

      - name: Upload coverage report to GitHub Pages (optional)
        run: coverage html  # Crée un rapport HTML

