name: FizzBuzz Tests  

on:
  push:  
    branches:
      - main  
  pull_request:  
    branches:
      - main  
  workflow_dispatch:  

jobs:
  test:  
    runs-on: ubuntu-latest  

    steps:
      - name: Cloner le dépôt  
        uses: actions/checkout@v3  

      - name: Configurer Python et installer les dépendances  
        uses: actions/setup-python@v4  
        with:
          python-version: "3.10"  
      
      - name: Installer les dépendances  
        run: |
          python -m pip install --upgrade pip  
          pip install -r requirements.txt || echo "No requirements.txt found"  

      - name: Exécuter les tests unitaires  
        run: |
          pip install unittest-xml-reporting  
          python -m xmlrunner discover -o test-reports/  
          python test_unitaire.py  

      - name: Explorer le concept de "code coverage"  
        run: |
          pip install coverage  
          coverage run -m unittest discover  
          coverage report -m > coverage.txt  # Sauvegarde le rapport dans un fichier

  deploy_docs:
    if: github.ref == 'refs/heads/main'  # Ne s'exécute que sur main
    needs: test  # Attend la fin du job "test" et ne s'exécute que s'il réussit
    runs-on: ubuntu-latest  
    steps:
      - name: Générer la documentation avec Sphinx  
        run: |
          pip install sphinx  
          sphinx-build -b html docs/source docs/build  

      - name: Déployer la documentation  
        run: |
          echo "Déploiement en cours..."
