name: Python Tests

on:
  push:
    branches:
      - main  # Exécute les tests lorsque tu pushes sur la branche principale
  pull_request:
    branches:
      - main  # Exécute les tests lorsque tu fais une pull request vers la branche principale
  workflow_dispatch:  # Permet de lancer les tests à la demande depuis GitHub

jobs:
  test:
    runs-on: ubuntu-latest  # Utilise un environnement Ubuntu pour l'exécution des tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Récupère le code source de ton dépôt

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Utilise la version 3 de Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Mets à jour pip
          pip install -r requirements.txt  # Installe toutes les dépendances listées dans requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover -s . -p "test.py"  # Lance les tests dans le fichier test.py (ou test_main.py si tu l'appelles ainsi)
