name: Run FizzBuzz Tests with unittest

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies (if needed)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "No requirements file found"

      - name: Run tests
        run: python -m unittest testunitaire.py

      - name: Block PR if tests fail
        if: failure()
        run: exit 1

  on-main:
    name: Actions spécifiques sur main
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publier les logs ou d'autres actions
        run: echo "Tests validés sur main, actions spécifiques possibles"
