name: FizzBuzz Tests

on:
  push:
    branches:
      - main  # Exécuter les tests après chaque push sur main
  pull_request:
    branches:
      - main  # Exécuter les tests sur chaque PR vers main
  workflow_dispatch:  # Permet d'exécuter les tests manuellement depuis GitHub

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Cloner le dépôt
        uses: actions/checkout@v3

      - name: 🐍 Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 📦 Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "No requirements.txt found"

      - name: 🧪 Exécuter les tests unitaires
        run: python test_unitaire.py
