name: FizzBuzz Tests 

on:
  push:  
    branches:
      - main  
  pull_request:  
    branches:
      - main  
  workflow_dispatch:  

jobs:
  test:  
    runs-on: ubuntu-latest  

    steps:
      - name: Cloner le dépôt  
        uses: actions/checkout@v3  

      - name: Configurer Python  
        uses: actions/setup-python@v4  
        with:
          python-version: "3.10"  

      - name: Installer les dépendances  
        run: |
          python -m pip install --upgrade pip  
          pip install -r requirements.txt || echo "No requirements.txt found"  
      - name: Exécuter les tests unitaires  
        run: |
          pip install unittest-xml-reporting  
          python -m xmlrunner discover -o test-reports/  
          python test_unitaire.py  
      - name: Explorer le concept de "code coverage" en exécution locale  
        run: |
          pip install coverage  
          coverage run -m unittest discover  
          coverage report -m  
      - name: Explorer la couverture de code en local et sur GitHub Actions  
        run: |
          pip install coverage
          coverage run -m unittest discover  
          coverage report -m  